
import java.awt.Dimension;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author javi2
 */
public class preguntas extends javax.swing.JPanel {

    /**
     * Creates new form preguntas
     */
    
    public preguntas() {
        initComponents();
        
        Dimension dimension = new Dimension(335,195);
        utilidades.SetImageLabel(fondo, "src/imagenes/Panel_Principal.png", dimension); 
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pregunta = new javax.swing.JLabel();
        menos = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setForeground(new java.awt.Color(5, 19, 36));
        jPanel1.setMaximumSize(new java.awt.Dimension(340, 370));
        jPanel1.setMinimumSize(new java.awt.Dimension(340, 370));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(340, 370));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pregunta.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        pregunta.setForeground(new java.awt.Color(255, 255, 255));
        pregunta.setText("Pregunta");
        jPanel1.add(pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        menos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Menos_Off.png"))); // NOI18N
        menos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menos.setMaximumSize(new java.awt.Dimension(30, 30));
        menos.setMinimumSize(new java.awt.Dimension(30, 30));
        menos.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(menos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 20, 20));

        fondo.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Panel_Principal.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel menos;
    private javax.swing.JLabel pregunta;
    // End of variables declaration//GEN-END:variables
}
